name: Fly Deploy Production
on:
  push:
    branches:
      - production
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  ROLLBAR_API_KEY: ${{ secrets.ROLLBAR_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
defaults:
  run:
    working-directory: packages/nouns-api
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'packages/nouns-api/**'
          base: 'production'
      # run only if 'api' files were changed
      - name: api deploy
        if: steps.filter.outputs.api == 'true'
        run: flyctl deploy --remote-only --config ./fly.toml
