name: Fly Deploy Staging
on:
  push:
    branches:
      - staging
      - master
env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
defaults:
  run:
    working-directory: packages/nouns-api
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            api:
              - 'packages/nouns-api/**'
      # run only if 'api' files were changed
      - name: api deploy
        if: steps.filter.outputs.api == 'true'
        run: flyctl deploy --remote-only --config ./fly.staging.toml
